# Site settings
baseURL = "/"
languageCode = "en-us"
title = "Raula Gaikovina Kula"
theme = "forty"

# Enter your tracking code to enable Google Analytics
googleAnalytics = ""

# Enter your disqus shortname to enable comments
disqusShortname = ""

[params]
  # You can use Markdown syntax for urls [text](//url.to/source)
  # To create multi-line text in strings use the """example Text""" format
  #
  # All icons using Fontawesome's icon font. Look at fontawesome.io/icons
  # for more icons. The icons are represented by their corresponding
  # CSS class.

  # Provide your metadata here.
  name = "Raula"
  description = "Your description"

  # Link custom assets relative to /static
  custom_css = []
  custom_js  = []
  favicon    = "favicon.ico"

  # Just a custom image variable, please define it in .md files for content.
  image = ""

  # 404 error customization
  [params.error404]
    heading = "Page couldn't be found"
    text = "Please visit [this page](/)"

  # Navigation Section
  [params.navigation]
    title = "Raula Gaikovina Kula"
    subtitle = "-raula-k@@is.naist.jp"
    menu = "Menu"
    # Optional logo as brand stored in img/
    # logo = "logo.png"

    [[params.navigation.links]]
      name = "Home"
      url = "#"

    [[params.navigation.links]]
      name = "Publications"
      url = "blogs/ipsum"

    [[params.navigation.links]]
      name = "Research"
      url = "blogs/ipsum"

    #[[params.navigation.links]]
    #  name = "Elements"
    #  url = "elements.html"

    # Add custom links here by uncommenting code below. To remove links just delete
    # the [[params.navigation.links]] map associated with that link. Copy and paste
    # code below if you need more links. Buttons work in the same way.
    # [[params.navigation.links]]
    #    name = "NameOfLink"
    #    url = "UrlOfLink"

    # Button Style 1
    #[[params.navigation.button1]]
    #  name = "Get Started"
    #  url = "blogs"

    # Button Style 2
    #[[params.navigation.button2]]
    #  name = "Log In"
    #  url = "#"


  # Banner section
  [params.banner]
    # To change the background image on the homepage banner, replace 'banner.jpg' in
    # the 'static/img' folder.
    title = "Raula Gaikovina Kula, PhD"
    subtitle = """@NAIST Software Engineering Lab, as an Assistant Professor. Interests include technical (code) and (society) social developer aspects relationships within an ecosystem of evolving software """
    buttonText = "Show Me"

 # Section Type Two
  [params.two]
    enable = true
    title = "Upcoming in 2020"
    subtitle = """ 
    * Visit Prof. to Ecole de Technologie Superieure, Montreal, Canada
    * Visit U of Waterloo , Canada
    * Visit Concordia, Canada
    * Visit McGill U, Canada
    * Visit Queens U, Canada
    * Visit Ecole de Polytechnique Montreal, Canada
    * ICSE2021 PC
    * ASE2020 PC 
    * ICSME2020 PC
    * SCAM2020 PC
    * MSR2020 PC
    * MSR2020 Data PC
    * ASE2020 PC
    * ESEM2020 PC
    * ICPC2020 PC
    * SANER2020 PC
    * EASE2020 Short Paper PC
    * OPENSYM2020 PC
    * VISSOFT2020 PC
    * ICSR2020 PC
    * ICGSE2020 PC
    * SoHeal2020 OC 
    * ICSME2020 OC
    * Associate Editor Science of Computer Programming (Special Issue)
    * Associate Editor IEICE (Special Issue)
    * Trans IEICE (Japanese)
    * IEEE Transactions on Sofware Engineering Reviewer
    * Springer Empirical Software Engineering Reviewer
    * Elsevier Information Software Technology Reviewer
    * Elsevier Journal of Systems and Software Reviewer
    * Software Quality Journal
    * IPSJ (Japanese)
    * IEEE Software *"""
    buttonText = "See up to 2019"
    url = "Updates"

  # Tiles Section
  [params.tiles]
    enable = true
    # Display your showcases here.
    
    [[params.tiles.showcase]]
      title = "Publications"
      subtitle = "Full List of Publications"
      image = "pic01.jpg"
      url = "blogs/aliquam"

    [[params.tiles.showcase]]
      title = "My Research & Collaborations"
      subtitle = "Research Projects and Presentations"
      image = "pic02.jpg"
      url = "blogs/aliquam"

    [[params.tiles.showcase]]
      title = "Community Service"
      subtitle = "List of Program Committee, Organization Chairs and other fun stuff"
      image = "pic03.jpg"
      url = "blogs/magna"

  [params.blog]
    # All blogs defined in their own files. You can find example blogs
    # at 'exampleSite/content/blogs'. Copy the 'blogs' folder into the 'content' directory
    # at the root of this Hugo site.
    # For more informtion take a look at the README.
    # To add more blogs just copy and paste the code.

 

  # Contact section
  [params.contact]
    enable = false
    buttonSend = "Send message"
    buttonClear = "Clear"

    # Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your email address under 'email' below and uncomment
    # - upload the generated site to your server
    # - send a dummy email yourself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!
    # formEmail = "example@domain.com"

    # Contact Section
    # You can add multiple emails, phone numbers, or addresses
    # by copying the corresponding map with frontmatter code.
    [[params.contact.email]]
    title = "Email"
    email = "example@domain.com"

    [[params.contact.phone]]
    title = "Phone"
    phone = "(000) 000-0000 x1234"

    [[params.contact.address]]
    title = "Address"
    street = "Street"
    city = "City, ST 00000"
    country = "Country"

  # Footer section
  [params.footer]
    enable = true
    #copyright = "Company Name"

    # Uses font awesome icons
    [[params.footer.social]]
      icon = "fa-twitter"
      url= "https://twitter.com/hashtag/raux"
      label = "Twitter"

    [[params.footer.social]]
      icon = "fa-facebook"
      url= "https://www.facebook.com/au.gai.9"
      label = "Facebook"

    #[[params.footer.social]]
    #  icon = "fa-instagram"
    # url= "https://www.instagram.com"
    # label = "Instagram"
    
    [[params.footer.social]]
      icon = "fa-github"
      url= "https://www.github.com"
      label = "GitHub"

    [[params.footer.social]]
      icon = "fa-linkedin"
      url= "https://www.linkedin.com"
      label = "LinkedIn"

    [[params.footer.quicklinks]]
      text = "Design: "
      url= "https://www.html5up.net"
      alt = "HTML5 UP"
